jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    default_context:
        serialization:
            serialize_null: true

    metadata:
        auto_detection: true
        directories:
            config:
                namespace_prefix: "App\\Presentation\\DTO"
                path: "%kernel.project_dir%/config/infrastructure/serializer"

when@prod:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION

when@dev:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_PRETTY_PRINT
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION
