services:
  php_auth_service:
    container_name: php
    build:
      context: .
      dockerfile: ./devops/docker/php/Dockerfile
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - .:/var/www/html/auth-service:rw
      -  /projetos/auth-service/config/infrastructure/certificado:/certificates
      - ./devops/docker/php/php.ini:/usr/local/etc/php/php.ini
#      - ./devops/docker/php/php.ini:/usr/local/etc/php/php.ini
#      - ./devops/docker/php/php.ini-production:/usr/local/etc/php/php.ini-production
    networks:
      - external-net
    extra_hosts:
      - redis:host-gateway

  apache2_auth_service:
    container_name: apache
    build:
      context: .
      dockerfile: ./devops/docker/apache/Dockerfile
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 3031:80
    volumes:
      - .:/var/www/html/auth-service:rw
      - ./devops/docker/apache/vhosts/default.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - external-net
    depends_on:
      - php_auth_service

  db_auth_service:
    container_name: postgres
    build:
      context: .
      dockerfile: ./devops/docker/postgres/Dockerfile
#    restart: always
    environment:
      POSTGRES_DB: 'auth_service'
      POSTGRES_USER: 'user_auth_service'
      POSTGRES_PASSWORD: 'authservice'
    ports:
      - 5432:5432
    volumes:
      - .:/var/lib/postegresql/data:rw
      - ./devops/docker/postgres/create_fixtures.sql:/docker-entrypoint-initdb.d/create_fixtures.sql
    networks:
      external-net:

networks:
  external-net:
    external: true