App\Presentation\DTO\Authorize\AuthorizeRequest:
  properties:
    responseType:
      - NotBlank: { message: 'invalid_request' }
      - App\Infrastructure\Validator\Constraint\Authorize\ResponseTypeInvalidConstraint: ~
    clientId:
      - NotBlank: { message: 'invalid_request' }
      - App\Infrastructure\Validator\Constraint\Common\ClientIdInvalidConstraint: ~
    redirectUri:
      - NotBlank: ~
      - App\Infrastructure\Validator\Constraint\Common\RedirectUriInvalidConstraint: ~
    scope:
      - NotBlank: { message: 'invalid_request' }
    state:
      - NotBlank: { message: 'invalid_request' }