App\Domain\VO\AuthenticationVO:
  properties:
    responseType:
      - NotBlank: ~
    clientId:
      - NotBlank: ~
    redirectId:
      - NotBlank: ~
    scope:
      - NotBlank: ~
    state:
      - NotBlank: ~
    email:
      - NotBlank: ~
      - Email: ~
    password:
      - NotBlank: ~
