App\Presentation\DTO\Login\LoginRequest:
  properties:
    _token:
      - App\Infrastructure\Validator\Constraint\Login\TokenInvalidConstraint: ~
    email:
      - NotBlank: { message: 'invalid_request' }
      - App\Infrastructure\Validator\Constraint\Login\EmailNotExistConstraint: ~
      - Email: ~
    password:
      - NotBlank: { message: 'invalid_request' }
      - App\Infrastructure\Validator\Constraint\Login\PasswordInvalidConstraint: ~