App\Domain\VO\SingUpVO:
  exclusion_policy: ALL
  properties:
    username:
      - NotBlank: ~
    email:
      - NotBlank: ~
      - Email: ~
    password:
      - NotBlank: ~
    scopes:
      - NotBlank: ~
