App\Presentation\DTO\Token\TokenRequest:
  properties:
    grantType:
      - NotBlank: { message: 'invalid_request' }
      - App\Infrastructure\Validator\Constraint\Token\GrantTypeInvalidConstraint: ~
    code:
      - NotBlank: { message: 'invalid_request' }
      - App\Infrastructure\Validator\Constraint\Token\CodeExpireConstraint: ~
    clientId:
      - NotBlank: { message: 'invalid_request' }
      - App\Infrastructure\Validator\Constraint\Common\ClientIdInvalidConstraint: ~
    clientSecret:
      - NotBlank: { message: 'invalid_request' }
      - App\Infrastructure\Validator\Constraint\Token\ClientSecretInvalidConstraint: ~
    redirectUri:
      - NotBlank: { message: 'invalid_request' }
      - App\Infrastructure\Validator\Constraint\Common\RedirectUriInvalidConstraint: ~
